// MIT License — see LICENSE
//
// D-03's derived, human-readable Markdown dashboard: a priority-sorted
// table (QUEUE-02's ordering, via scripts/queue/priority.mjs's
// sortByPriority — never re-derived here) + per-status counts + the
// D-06 close-rate throughput metric (present from day one) + an
// advisory WIP-limit line on the `fixing` status (never a hard block —
// Pitfall 7/D-06). This is a VIEW, regenerated by script whenever the
// queue changes — never hand-edited; the JSON queue file
// (test/fixtures/fix-queue.json) remains the only source of truth.
//
// Run with: npx tsx scripts/queue/dashboard.mjs
// (NOT plain `node` — this script's src/ + test/ imports use
// .js-suffixed specifiers pointing at sibling .ts files; Node's native
// TS type-stripping does not rewrite .js -> .ts, so plain node fails
// with ERR_MODULE_NOT_FOUND on the first such import. tsx resolves this
// correctly, and so does vitest's own resolver when this module is
// imported from a .test.ts file — see scripts/queue/intake.mjs's
// header for the same note.)

import { join } from "node:path";

import { isMainModule } from "../test-with-sentinel.mjs";
import { sortByPriority } from "./priority.mjs";

import { writeFileAtomic } from "../../src/session/safe-source-io.js";
import { SERVER_REPO_ROOT } from "../../src/repo-root.js";
import { fixQueue } from "../../test/fixtures/fix-queue.js";

// D-06's advisory-only WIP-limit default on the `fixing` status
// (Claude's discretion, per 04-CONTEXT.md) — a simple, easily-adjusted
// constant. Deliberately never a hard block: a hard intake block would
// manufacture exactly the evaporation QUEUE-01 exists to prevent
// (Pitfall 7/D-06).
const WIP_LIMIT = 3;

// Statuses that count as "closed" for the D-06 close-rate/throughput
// metric — a terminal state, one way or another (fixed-and-locked, or
// deliberately rejected).
const CLOSED_STATUSES = new Set(["locked", "rejected"]);

/** Escapes a literal `|` so free-text fields (e.g. `title`) can never
 *  break the surrounding markdown table's column structure. */
function escapeTableCell(value) {
  // Escape pipes AND collapse newlines to a space — a literal newline in
  // a cell breaks the markdown table row this function exists to protect.
  return String(value).replaceAll("|", "\\|").replace(/[\r\n]+/gu, " ");
}

function renderTableRow(entry) {
  const fingerprint = entry.fingerprint.slice(0, 8);
  const triageClass = entry.triageClass ?? "(none)";
  return `| ${fingerprint} | ${entry.status} | ${entry.defectKind} | ${triageClass} | ${escapeTableCell(entry.title)} | ${entry.recurrence} |`;
}

/** Builds the priority-sorted table from an ALREADY-sorted entries
 *  array — callers must pass `sortByPriority(entries)`'s own output,
 *  never re-sort here, so the table's row order can never drift from
 *  QUEUE-02's own ordering (scripts/queue/priority.mjs). */
function renderTable(sortedEntries) {
  const header = "| Fingerprint | Status | DefectKind | TriageClass | Title | Recurrence |";
  const divider = "| --- | --- | --- | --- | --- | --- |";
  const rows = sortedEntries.map(renderTableRow);
  return [header, divider, ...rows].join("\n");
}

/** One line per distinct `status` value present in `entries`, in
 *  first-seen order — never a fixed enum-order list, so an unexpected
 *  future status still shows up rather than being silently dropped. */
function renderStatusCounts(entries) {
  const counts = new Map();
  for (const entry of entries) {
    counts.set(entry.status, (counts.get(entry.status) ?? 0) + 1);
  }
  if (counts.size === 0) {
    return "- (no entries)";
  }
  return [...counts.entries()].map(([status, count]) => `- ${status}: ${count}`).join("\n");
}

/** The D-06 close-rate/throughput metric, present from day one:
 *  closed (locked or rejected) over total. */
function renderCloseRate(entries) {
  const total = entries.length;
  const closed = entries.filter((entry) => CLOSED_STATUSES.has(entry.status)).length;
  return `**close-rate:** ${closed}/${total}`;
}

/** The advisory (never a hard block) WIP-limit line on the `fixing`
 *  status — a warning once the count exceeds WIP_LIMIT, an informational
 *  line otherwise. */
function renderWipLimit(entries) {
  const fixingCount = entries.filter((entry) => entry.status === "fixing").length;
  if (fixingCount > WIP_LIMIT) {
    return `WARNING: ${fixingCount} entries in fixing exceeds the advisory WIP limit of ${WIP_LIMIT}`;
  }
  return `${fixingCount} entries in fixing (advisory WIP limit: ${WIP_LIMIT})`;
}

/**
 * Render the D-03 dashboard as a markdown string. PURE — no
 * `Date.now()`/live timestamp anywhere in the returned string, so the
 * output is deterministically testable for the same `entries` input
 * every time. Sections, in order: (1) title + regenerated-view notice,
 * (2) the priority-sorted table (via `sortByPriority`, imported from
 * ./priority.mjs — never re-derived here), (3) per-status counts,
 * (4) the close-rate metric, (5) the advisory WIP-limit line.
 */
export function renderDashboard(entries) {
  const sorted = sortByPriority(entries);
  return [
    "# Fix Queue Dashboard",
    "",
    "_Regenerated by `scripts/queue/dashboard.mjs` — never hand-edit. " +
      "The JSON queue file (test/fixtures/fix-queue.json) is the only source of truth (D-03)._",
    "",
    renderTable(sorted),
    "",
    "## Per-Status Counts",
    "",
    renderStatusCounts(entries),
    "",
    "## Throughput",
    "",
    renderCloseRate(entries),
    "",
    "## WIP",
    "",
    renderWipLimit(entries),
    "",
  ].join("\n");
}

/**
 * Regenerate the dashboard file at `dashboardPath` from `entries`, via
 * the same crash-safe atomic write (temp-file + rename) every other
 * repeatedly-hand-run queue script uses — concurrent readers never
 * observe a half-written dashboard (T-04-05-01).
 */
export async function regenerateDashboard(entries, dashboardPath) {
  await writeFileAtomic(dashboardPath, renderDashboard(entries));
}

// ── CLI ──────────────────────────────────────────────────────────────

/**
 * CLI entry point: regenerates docs/FIX-QUEUE-DASHBOARD.md from the
 * REAL fixQueue export (test/fixtures/fix-queue.js) — never a synthetic
 * placeholder. Run whenever the queue file changes (D-03's regeneration
 * trigger is manual-first, mirroring D-08's own manual-first status
 * transitions).
 */
export async function scriptMain() {
  const dashboardPath = join(SERVER_REPO_ROOT, "docs/FIX-QUEUE-DASHBOARD.md");
  await regenerateDashboard(fixQueue, dashboardPath);
  process.stdout.write(`Regenerated ${dashboardPath}\n`);
}

if (isMainModule(import.meta.url, process.argv[1])) {
  await scriptMain();
}
